"""The launch logo: a rearing bay horse, drawn in half-block pixels.

Each character cell holds two vertical pixels (a half block with a foreground
colour for the top pixel and a background colour for the bottom one), so a
33 x 38 pixel drawing takes 33 x 19 cells. The drawing is original: a bay with a
black mane, tail and lower legs, a white blaze and one white sock.
"""
from __future__ import annotations

from rich.style import Style
from rich.text import Text

PALETTE = {
    "B": "#b3602b",  # bay coat
    "S": "#7d3f1b",  # shaded coat
    "L": "#d98a4c",  # highlight
    "N": "#1d1714",  # mane, tail, lower legs
    "W": "#f3eee6",  # blaze and sock
    "H": "#8d8a86",  # hooves
}

ART = """
.....................BB.S........
....................NNNSSS.......
...................NNNNSBBW......
..................NNNNNSBBWW.....
.................NNNNNNBNSLW.....
...................NNNBBSBBWW....
.................NNNNNBBBBBLWW...
...............NNNNNNBBBBBBBLW...
..................NNNBBBBBBBBWW..
.................NNNSBBBBBBBBLH..
...............NNNNNBBBB..BBBSS..
..............NN.SNNBBBB...BBSS..
................NNNSBBB...BB.....
...............SNNNSBBBBBSNN.....
.............BSNSNNBBBBBBSNNS....
............BBSBNNSLLBBBBSNNN....
...........BBBBSNBBLLBBBB.NNN....
...........BBBSSBBBLLBB....NNN...
..........BBBBBBBBBLBBBBBBBSSH...
..........BBBBBBBBBBBBBBSNSHHH...
.........BBBBBBBBBBBBBBBSNNBHH...
.........BBBBBBBBBSSBBBBSNN......
.........BBBBBBBBSSSB....NN......
........BBBBBBBBBSSB.....NN......
.......NBBBBBBBBSSBB.....HHH.....
......NNBBBBBBBBSSB......HHH.....
....NNNNSBBBBBBBSB.......HH......
...NNNNNNBBBBBBBB................
..NNNNNN..SBBBBBB................
..NNNNN...SSSBBBB................
.NNNNNN...SSSBSNNB...............
.NNNNN....NNS.SNNB...............
.NNNNN....NNN.SHH................
.NNNNN....NN...WW................
.NNNN....NNN...WW................
.NNNN....NNN...WWW...............
.........HHH...HHH...............
.................................
"""


def horse() -> Text:
    rows = [r for r in ART.strip("\n").split("\n")]
    width = max(len(r) for r in rows)
    rows = [r.ljust(width, ".") for r in rows]
    if len(rows) % 2:
        rows.append("." * width)
    out = Text()
    for top, bottom in zip(rows[0::2], rows[1::2]):
        for a, b in zip(top, bottom):
            ca, cb = PALETTE.get(a), PALETTE.get(b)
            if ca and cb:
                out.append("▀", Style(color=ca, bgcolor=cb))
            elif ca:
                out.append("▀", Style(color=ca))
            elif cb:
                out.append("▄", Style(color=cb))
            else:
                out.append(" ")
        out.append("\n")
    out.rstrip()
    return out
